### ISSUE TITLE
Build 1167 not loading properly but causing system instability on 7.02 (error CE-36329-3)

### ISSUE THREAD

**Issue by hippie68** [OSM-Made/Orbis-Toolbox#34]
I'm reporting this because it says "7.02 confirmed working by testers".
The error CE-36329-3 keeps showing up every few seconds until reboot.

 - Firmware: 702
 - Console Type: Slim
 - HEN 2.1.3b

**Comment by OSM-Made** [comment]
I believe its a problem with HEN 2.1.3 try using Mira or GoldHEN.

**Comment by rox898** [comment]
I have the same problem

**Comment by rox898** [comment]
there we have the problem. I have resys. do you know if it is enough to clean the ps4 and after that run in orbis?

**Comment by OSM-Made** [comment]
If you re-install the fw from the safe mode or the xmb I believe it gets rid of it.

**Comment by rox898** [comment]
Thx :)
